version: '3.8'

services:
  composer:
    image: composer:2.4
    volumes:
      - .:/app

  phpunit:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
